config:
    database:
        hostname: localhost
        username: root
        password: bucht
        name: oauth2

    hikingroutes:
        clientId: myroutes
        clientSecret: 5LK36bGnTKc23Dl1dXY

    memcached:
        hostname: localhost
        port: 11211
        prefix: oauthserver_
